# Generated by Django 5.0.6 on 2024-06-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('weight', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='patientdata',
            name='medication',
        ),
        migrations.AddField(
            model_name='patientdata',
            name='medication',
            field=models.ManyToManyField(related_name='names', to='account.medicine'),
        ),
    ]
