# Generated by Django 5.0.6 on 2024-06-15 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='00000000', max_length=15, unique=True),
        ),
    ]
