# Generated by Django 5.0.6 on 2024-06-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='emergency_contact_number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='emergency_contact',
            field=models.CharField(max_length=25),
        ),
    ]
