# Generated by Django 5.0.6 on 2024-06-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_profile_emergency_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_appointment',
            field=models.DateField(blank=True, null=True),
        ),
    ]
