# Generated by Django 5.0.6 on 2024-06-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_profile_last_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='orders',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
