# Generated by Django 5.0.6 on 2024-06-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_profile_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='orders',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
